name: Windows

on: [push, pull_request]
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: dependencies
        run: |
          choco install make cmake
      - name: build
        shell: bash
        run: |
          cmake . -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_SANITIZERS=On
          make
      - name: test
        shell: bash
        run: |
          make check
