name: Windows

on: [push, pull_request]
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: dependencies
        run: |
          choco install make cmake
      - name: build
        run: |
          mkdir build
          cd build
          cmake .. -DCOVERAGE_ENABLED=Off
          make
      - name: test
        run: |
          make -C test
